/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instruktur;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import overskill.DBConnect;
import overskill.InstrukturPage;

/**
 *
 * @author samod
 */
public class Jawaban_Siswa extends javax.swing.JFrame {
    DBConnect c = new DBConnect();
    String id_quiz_siswa = "";
    ArrayList<String> jawaban;
    ArrayList<String> soal;
    InstrukturPage ip;
    /**
     * Creates new form Jawaban
     */
    public Jawaban_Siswa() {
        initComponents();
        jawaban = new ArrayList<>();
        soal = new ArrayList<>();
    }
    
    public Jawaban_Siswa(InstrukturPage ip, String id_quiz_siswa) {
        initComponents();
        this.ip = ip;
        this.id_quiz_siswa = id_quiz_siswa;
        jawaban = new ArrayList<>();
        soal = new ArrayList<>();
        formLoad(id_quiz_siswa);
    }
    
    private void formLoad(String id_quiz_siswa) {
        try 
        {
            c.stat = c.conn.createStatement();
            String sql = "SELECT * FROM viewJawaban_Siswa WHERE ID_QuizSiswa='" + id_quiz_siswa + "'";
            c.result = c.stat.executeQuery(sql);
            
            while(c.result.next()) {
                ResultSet r = c.result;
                jawaban.add(r.getString("Jawaban"));
                soal.add(r.getString("Soal"));
                lblJudul.setText(r.getString("Nama_Kelas") + " - " + r.getString("Judul") + " - " + r.getString("Nama_Siswa"));
            }
            
            c.stat.close();
            c.result.close();
            
            lblSoal1.setText("1. " + soal.get(0));
            lblSoal2.setText("2. " + soal.get(1));
            lblSoal3.setText("3. " + soal.get(2));
            lblSoal4.setText("4. " + soal.get(3));
            lblSoal5.setText("5. " + soal.get(4));
            
            txtArea1.setText(jawaban.get(0));
            txtArea2.setText(jawaban.get(1));
            txtArea3.setText(jawaban.get(2));
            txtArea4.setText(jawaban.get(3));
            txtArea5.setText(jawaban.get(4));
        } 
        catch(SQLException e) 
        {
            System.out.println("Terjadi error saat load data jawaban siswa "  + e);
        }
    }
    
    
    private void saveData() {
        int nilai = (int)txtNilai.getValue();
        
        try {
            String query = "UPDATE Quiz_Siswa SET Nilai=?, Komentar=? WHERE ID_QuizSiswa=?";

            try (PreparedStatement p = c.conn.prepareStatement(query)) {
                p.setFloat(1, nilai);
                p.setString(2, txtKomentar.getText());
                p.setString(3, id_quiz_siswa);
                
                p.executeUpdate();
            }

        } catch(SQLException e) {
            System.out.println("Terjadi error pada saat tambah quiz siswa : " + e);
        }


        JOptionPane.showMessageDialog(this, "Data nilai berhasil disimpan.", "Berhasil",  JOptionPane.INFORMATION_MESSAGE);   

        ip.newSubmissionSiswa(ip);
    }
    
    
    public JPanel getPanel() {
        return PanelContent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContent = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblSoal1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        lblSoal2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea3 = new javax.swing.JTextArea();
        lblSoal3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea4 = new javax.swing.JTextArea();
        lblSoal4 = new javax.swing.JLabel();
        lblSoal5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtArea5 = new javax.swing.JTextArea();
        btnKembali = new components.MaterialButton();
        btnNilai = new components.MaterialButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNilai = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtKomentar = new org.jdesktop.swingx.JXTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        PanelContent.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelContentformComponentShown(evt);
            }
        });
        PanelContent.setLayout(new javax.swing.BoxLayout(PanelContent, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(954, 75));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("Submission");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(491, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJudul))
        );

        PanelContent.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));
        jPanel4.setMaximumSize(new java.awt.Dimension(327812, 327812));

        lblSoal1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSoal1.setText("1. Apa itu konsep OOP pada Java?");

        txtArea1.setColumns(20);
        txtArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtArea1.setRows(3);
        txtArea1.setEnabled(false);
        txtArea1.setPreferredSize(new java.awt.Dimension(200, 94));
        jScrollPane1.setViewportView(txtArea1);

        lblSoal2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSoal2.setText("2.");

        txtArea2.setColumns(20);
        txtArea2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtArea2.setRows(3);
        txtArea2.setEnabled(false);
        txtArea2.setPreferredSize(new java.awt.Dimension(200, 94));
        jScrollPane2.setViewportView(txtArea2);

        txtArea3.setColumns(20);
        txtArea3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtArea3.setRows(3);
        txtArea3.setEnabled(false);
        txtArea3.setPreferredSize(new java.awt.Dimension(200, 94));
        jScrollPane3.setViewportView(txtArea3);

        lblSoal3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSoal3.setText("2.");

        txtArea4.setColumns(20);
        txtArea4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtArea4.setRows(3);
        txtArea4.setEnabled(false);
        txtArea4.setPreferredSize(new java.awt.Dimension(200, 94));
        jScrollPane4.setViewportView(txtArea4);

        lblSoal4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSoal4.setText("2.");

        lblSoal5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSoal5.setText("2.");

        txtArea5.setColumns(20);
        txtArea5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtArea5.setRows(3);
        txtArea5.setEnabled(false);
        txtArea5.setPreferredSize(new java.awt.Dimension(200, 94));
        jScrollPane5.setViewportView(txtArea5);

        btnKembali.setBackground(new java.awt.Color(255, 214, 207));
        btnKembali.setForeground(new java.awt.Color(255, 92, 64));
        btnKembali.setText("Kembali");
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnNilai.setBackground(new java.awt.Color(40, 167, 69));
        btnNilai.setText("Beri Nilai");
        btnNilai.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNilaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Penilaian");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Jawaban");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Nilai");

        txtNilai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNilai.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        txtNilai.setPreferredSize(new java.awt.Dimension(29, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Komentar");

        txtKomentar.setColumns(20);
        txtKomentar.setRows(5);
        jScrollPane6.setViewportView(txtKomentar);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSoal5)
                    .addComponent(lblSoal4)
                    .addComponent(lblSoal3)
                    .addComponent(lblSoal2)
                    .addComponent(lblSoal1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane5))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6)
                    .addComponent(txtNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2)
                    .addContainerGap(1019, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoal1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSoal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoal4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoal5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(536, Short.MAX_VALUE)))
        );

        PanelContent.add(jPanel4);

        getContentPane().add(PanelContent);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelContentformComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelContentformComponentShown
        formLoad(id_quiz_siswa);
    }//GEN-LAST:event_PanelContentformComponentShown

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        ip.newSubmissionSiswa(ip);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNilaiActionPerformed
        int nilai = (int)txtNilai.getValue();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menilai quiz ini dengan nilai " + String.valueOf(nilai) + "?",
                "Peringatan", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            saveData();
        }
    }//GEN-LAST:event_btnNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jawaban_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jawaban_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jawaban_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jawaban_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jawaban_Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private components.MaterialButton btnKembali;
    private components.MaterialButton btnNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblSoal1;
    private javax.swing.JLabel lblSoal2;
    private javax.swing.JLabel lblSoal3;
    private javax.swing.JLabel lblSoal4;
    private javax.swing.JLabel lblSoal5;
    private javax.swing.JTextArea txtArea1;
    private javax.swing.JTextArea txtArea2;
    private javax.swing.JTextArea txtArea3;
    private javax.swing.JTextArea txtArea4;
    private javax.swing.JTextArea txtArea5;
    private org.jdesktop.swingx.JXTextArea txtKomentar;
    private javax.swing.JSpinner txtNilai;
    // End of variables declaration//GEN-END:variables
}
