/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overskill;

import components.MaterialButton;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import admin.Instruktur;
import admin.Kelas;
import admin.Komputer;
import admin.Siswa;
import admin.User;
import admin.User;
import admin.Jadwal;
import admin.Pendaftaran;


/**
 *
 * @author ERROR404
 */
public class AdminPage extends javax.swing.JFrame {

    // Deklarasi Layout Menu.
    CardLayout contentLayout;
    
    // Deklarasi Variabel Fungsi Maximize
    private int width = 240;
    private boolean state = true;
    
    public AdminPage() 
    {
        initComponents();
        
        // Mengganti nama user dengan nama akun yang sudah login.
        User u = new User();
        Instruktur ins = new Instruktur();
        Komputer kom = new Komputer();
        Siswa sis = new Siswa();
        Kelas kel = new Kelas();
        Jadwal jad = new Jadwal();
        Dashboard d = new Dashboard();
        Pendaftaran p = new Pendaftaran();
        
        Content.add("dashboard", d);
        
        Content.add("masterUser", u.getPanel());
        Content.add("masterInstruktur", ins.getPanel());
        Content.add("masterKomputer", kom.getPanel());
        Content.add("masterSiswa", sis.getPanel());
        Content.add("masterKelas", kel.getPanel());
        Content.add("masterJadwal", jad.getPanel());
        Content.add("pendaftaran", p.getPanel());
        
        contentLayout = (CardLayout) Content.getLayout();   

        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        
        setMark(mark1);
        
        // Membuat Fungsi Sidebar menjadi full saat maximize.
        this.addWindowStateListener(new WindowStateListener() {

            @Override
            public void windowStateChanged(WindowEvent we) {
                frame__windowStateChanged(we);
            }
            
            public void frame__windowStateChanged(WindowEvent e){
                if ((e.getNewState() & JFrame.MAXIMIZED_BOTH) == JFrame.MAXIMIZED_BOTH){
                    width = 300;
                    topPanel.setDividerLocation(width);
                    bottomPanel.setDividerLocation(width);
                    //textRole.setText("Ladetani");
                    NavBrand.setMinimumSize(new Dimension(300, 50));
                    Slide.setMinimumSize(new Dimension(300, 50));
                    state = true;
                }
             }
        });
    }
    
    private void setMark(JPanel myPanel)
    {
        mark1.setVisible(false);
        mark2.setVisible(false);
        mark3.setVisible(false);
        mark4.setVisible(false);
        mark5.setVisible(false);
        mark6.setVisible(false);
        mark7.setVisible(false);
        mark8.setVisible(false);
        
        myPanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JSplitPane();
        Header = new javax.swing.JPanel();
        leftHeader = new javax.swing.JPanel();
        iconMenu = new javax.swing.JLabel();
        btnMenu = new MaterialButton();
        rightHeader = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLogout = new components.MaterialIconButton();
        NavBrand = new javax.swing.JPanel();
        iconOS = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JSplitPane();
        Slide = new javax.swing.JPanel();
        iconDriver = new javax.swing.JLabel();
        iconKelolaUser = new javax.swing.JLabel();
        btnMasterKomputer = new MaterialButton();
        btnMasterKelas = new MaterialButton();
        iconUser = new javax.swing.JLabel();
        textNama = new javax.swing.JLabel();
        iconJenis = new javax.swing.JLabel();
        btnMasterInstruktur = new MaterialButton();
        iconDashboard = new javax.swing.JLabel();
        btnDashboard = new MaterialButton();
        textRole = new javax.swing.JLabel();
        iconProdusen = new javax.swing.JLabel();
        btnMasterSiswa = new MaterialButton();
        iconProduk = new javax.swing.JLabel();
        btnMasterUser = new MaterialButton();
        mark1 = new javax.swing.JPanel();
        mark2 = new javax.swing.JPanel();
        mark3 = new javax.swing.JPanel();
        mark4 = new javax.swing.JPanel();
        mark5 = new javax.swing.JPanel();
        mark6 = new javax.swing.JPanel();
        iconDriver1 = new javax.swing.JLabel();
        btnMasterJadwal = new MaterialButton();
        mark7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        mark8 = new javax.swing.JPanel();
        iconDriver2 = new javax.swing.JLabel();
        btnMasterJadwal1 = new MaterialButton();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Overskill");
        setMinimumSize(new java.awt.Dimension(1280, 720));

        Container.setBorder(null);
        Container.setDividerLocation(50);
        Container.setDividerSize(0);
        Container.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        Container.setToolTipText("");
        Container.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Container.setPreferredSize(new java.awt.Dimension(804, 718));

        topPanel.setBorder(null);
        topPanel.setDividerLocation(300);
        topPanel.setDividerSize(0);

        Header.setBackground(new java.awt.Color(42, 79, 150));
        Header.setPreferredSize(new java.awt.Dimension(700, 52));
        Header.setLayout(new java.awt.GridLayout(1, 0));

        leftHeader.setBackground(new java.awt.Color(42, 64, 84));
        leftHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconMenu.setBackground(new java.awt.Color(42, 64, 84));
        iconMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_25px.png"))); // NOI18N
        leftHeader.add(iconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        btnMenu.setBackground(new java.awt.Color(42, 64, 84));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        leftHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        Header.add(leftHeader);

        rightHeader.setBackground(new java.awt.Color(42, 64, 84));
        rightHeader.setLayout(new javax.swing.BoxLayout(rightHeader, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(42, 64, 84));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        rightHeader.add(jPanel2);

        btnLogout.setBackground(new java.awt.Color(42, 64, 84));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutdown_25px.png"))); // NOI18N
        btnLogout.setMaximumSize(new java.awt.Dimension(110, 3224));
        btnLogout.setPreferredSize(new java.awt.Dimension(50, 33));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        rightHeader.add(btnLogout);

        Header.add(rightHeader);

        topPanel.setRightComponent(Header);

        NavBrand.setBackground(new java.awt.Color(245, 121, 0));
        NavBrand.setMaximumSize(new java.awt.Dimension(240, 32767));
        NavBrand.setPreferredSize(new java.awt.Dimension(240, 47));
        NavBrand.setLayout(null);

        iconOS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        iconOS.setForeground(new java.awt.Color(255, 255, 255));
        iconOS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iconOS.setText("OVERSKILL");
        iconOS.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        iconOS.setIconTextGap(10);
        NavBrand.add(iconOS);
        iconOS.setBounds(20, 0, 190, 50);

        topPanel.setLeftComponent(NavBrand);

        Container.setLeftComponent(topPanel);

        bottomPanel.setBorder(null);
        bottomPanel.setDividerLocation(300);
        bottomPanel.setDividerSize(0);
        bottomPanel.setMinimumSize(new java.awt.Dimension(148, 60));

        Slide.setBackground(new java.awt.Color(42, 64, 84));
        Slide.setPreferredSize(new java.awt.Dimension(98, 695));
        Slide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconDriver.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconDriver.setForeground(new java.awt.Color(255, 255, 255));
        iconDriver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/class_25px.png"))); // NOI18N
        iconDriver.setText("   Master Kelas");
        Slide.add(iconDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 390, 200, 50));

        iconKelolaUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconKelolaUser.setForeground(new java.awt.Color(255, 255, 255));
        iconKelolaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/computer_25px.png"))); // NOI18N
        iconKelolaUser.setText("   Master Komputer");
        Slide.add(iconKelolaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, 200, 50));

        btnMasterKomputer.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterKomputer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterKomputer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterKomputerActionPerformed(evt);
            }
        });
        Slide.add(btnMasterKomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 340, 295, 50));

        btnMasterKelas.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterKelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterKelasActionPerformed(evt);
            }
        });
        Slide.add(btnMasterKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 390, 295, 50));

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male_user_40px.png"))); // NOI18N
        Slide.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 50));

        textNama.setBackground(new java.awt.Color(255, 255, 255));
        textNama.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        textNama.setForeground(new java.awt.Color(255, 255, 255));
        textNama.setText("Samodra");
        Slide.add(textNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));

        iconJenis.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconJenis.setForeground(new java.awt.Color(255, 255, 255));
        iconJenis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/training_25px.png"))); // NOI18N
        iconJenis.setText("   Master Instruktur");
        Slide.add(iconJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 240, 200, 50));

        btnMasterInstruktur.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterInstruktur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterInstruktur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterInstruktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterInstrukturActionPerformed(evt);
            }
        });
        Slide.add(btnMasterInstruktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 240, 295, 50));

        iconDashboard.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconDashboard.setForeground(new java.awt.Color(255, 255, 255));
        iconDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard_25px.png"))); // NOI18N
        iconDashboard.setText("   Dashboard");
        Slide.add(iconDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 200, 50));

        btnDashboard.setBackground(new java.awt.Color(42, 64, 84));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        Slide.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, 295, 50));

        textRole.setBackground(new java.awt.Color(255, 255, 255));
        textRole.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        textRole.setForeground(new java.awt.Color(255, 255, 255));
        textRole.setText("Admin");
        Slide.add(textRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        iconProdusen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconProdusen.setForeground(new java.awt.Color(255, 255, 255));
        iconProdusen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_male_25px.png"))); // NOI18N
        iconProdusen.setText("   Master Siswa");
        Slide.add(iconProdusen, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 290, 200, 50));

        btnMasterSiswa.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterSiswa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterSiswaActionPerformed(evt);
            }
        });
        Slide.add(btnMasterSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 290, 295, 50));

        iconProduk.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconProduk.setForeground(new java.awt.Color(255, 255, 255));
        iconProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male_user_25px.png"))); // NOI18N
        iconProduk.setText("   Master User");
        Slide.add(iconProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 200, 50));

        btnMasterUser.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterUserActionPerformed(evt);
            }
        });
        Slide.add(btnMasterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 190, 295, 50));

        mark1.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark1Layout = new javax.swing.GroupLayout(mark1);
        mark1.setLayout(mark1Layout);
        mark1Layout.setHorizontalGroup(
            mark1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark1Layout.setVerticalGroup(
            mark1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 5, 50));

        mark2.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark2Layout = new javax.swing.GroupLayout(mark2);
        mark2.setLayout(mark2Layout);
        mark2Layout.setHorizontalGroup(
            mark2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark2Layout.setVerticalGroup(
            mark2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 5, 50));

        mark3.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark3Layout = new javax.swing.GroupLayout(mark3);
        mark3.setLayout(mark3Layout);
        mark3Layout.setHorizontalGroup(
            mark3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark3Layout.setVerticalGroup(
            mark3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 5, 50));

        mark4.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark4Layout = new javax.swing.GroupLayout(mark4);
        mark4.setLayout(mark4Layout);
        mark4Layout.setHorizontalGroup(
            mark4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark4Layout.setVerticalGroup(
            mark4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 5, 50));

        mark5.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark5Layout = new javax.swing.GroupLayout(mark5);
        mark5.setLayout(mark5Layout);
        mark5Layout.setHorizontalGroup(
            mark5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark5Layout.setVerticalGroup(
            mark5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 5, 50));

        mark6.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark6Layout = new javax.swing.GroupLayout(mark6);
        mark6.setLayout(mark6Layout);
        mark6Layout.setHorizontalGroup(
            mark6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark6Layout.setVerticalGroup(
            mark6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 5, 50));

        iconDriver1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconDriver1.setForeground(new java.awt.Color(255, 255, 255));
        iconDriver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schedule_25px.png"))); // NOI18N
        iconDriver1.setText("  Master Jadwal");
        Slide.add(iconDriver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 440, 200, 50));

        btnMasterJadwal.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterJadwal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterJadwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterJadwalActionPerformed(evt);
            }
        });
        Slide.add(btnMasterJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, 295, 50));

        mark7.setBackground(new java.awt.Color(255, 129, 5));
        mark7.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout mark7Layout = new javax.swing.GroupLayout(mark7);
        mark7.setLayout(mark7Layout);
        mark7Layout.setHorizontalGroup(
            mark7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark7Layout.setVerticalGroup(
            mark7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, 50));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(72, 88, 102));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 1));
        Slide.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, -1));

        mark8.setBackground(new java.awt.Color(255, 129, 5));

        javax.swing.GroupLayout mark8Layout = new javax.swing.GroupLayout(mark8);
        mark8.setLayout(mark8Layout);
        mark8Layout.setHorizontalGroup(
            mark8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        mark8Layout.setVerticalGroup(
            mark8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Slide.add(mark8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, 50));

        iconDriver2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        iconDriver2.setForeground(new java.awt.Color(255, 255, 255));
        iconDriver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user_male_25px.png"))); // NOI18N
        iconDriver2.setText("  Pendaftaran");
        Slide.add(iconDriver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 490, 200, 50));

        btnMasterJadwal1.setBackground(new java.awt.Color(42, 64, 84));
        btnMasterJadwal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMasterJadwal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMasterJadwal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterJadwal1ActionPerformed(evt);
            }
        });
        Slide.add(btnMasterJadwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 490, 295, 50));

        bottomPanel.setLeftComponent(Slide);

        Content.setBackground(new java.awt.Color(230, 230, 230));
        Content.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        Content.setLayout(new java.awt.CardLayout());
        bottomPanel.setRightComponent(Content);

        Container.setRightComponent(bottomPanel);

        getContentPane().add(Container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        Thread th = new Thread()
        {
            @Override
            public void run ()
            {
                try
                {
                    int lock = bottomPanel.getDividerLocation();
                    int size = lock;
                    for(int a=0;a<=60;a++)
                    {
                        
                        Thread.sleep(6);

                        if (lock == 300)
                        {
                            size -= 4;
                            if (size == 60)
                            {
                                iconOS.setText("OS");
                            }
                        }
                        else 
                        {
                            size += 4;
                            if (size == 300)
                            {
                                iconOS.setText("Overskill");
                            }
                        }
                        
                        bottomPanel.setDividerLocation(size);
                        topPanel.setDividerLocation(size);
                    }
                }
                catch (Exception ex)
                {
                    System.out.println("Terjadi Error Pada Button Menu: " + ex);
                }
            }
        }; th.start();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnMasterKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterKomputerActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "masterKomputer");
        setMark(mark5);
    }//GEN-LAST:event_btnMasterKomputerActionPerformed

    private void btnMasterKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterKelasActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "masterKelas");
        setMark(mark6);
    }//GEN-LAST:event_btnMasterKelasActionPerformed

    private void btnMasterInstrukturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterInstrukturActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "masterInstruktur");
        setMark(mark3);
    }//GEN-LAST:event_btnMasterInstrukturActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "dashboard");
        setMark(mark1);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnMasterSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterSiswaActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "masterSiswa");
        setMark(mark4);
    }//GEN-LAST:event_btnMasterSiswaActionPerformed

    private void btnMasterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterUserActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "masterUser");
        setMark(mark2);
    }//GEN-LAST:event_btnMasterUserActionPerformed

    private void btnNavLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLoginActionPerformed
        // TODO add your handling code here:
//        Landing ld = new Landing();
//        ld.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnNavLoginActionPerformed

    private void btnMasterJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterJadwalActionPerformed
        // TODO add your handling code here:
        contentLayout.show(Content, "masterJadwal");
        setMark(mark7);
    }//GEN-LAST:event_btnMasterJadwalActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMasterJadwal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterJadwal1ActionPerformed
        contentLayout.show(Content, "pendaftaran");
        setMark(mark8);
    }//GEN-LAST:event_btnMasterJadwal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Container;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel NavBrand;
    private javax.swing.JPanel Slide;
    private javax.swing.JSplitPane bottomPanel;
    private javax.swing.JButton btnDashboard;
    private components.MaterialIconButton btnLogout;
    private javax.swing.JButton btnMasterInstruktur;
    private javax.swing.JButton btnMasterJadwal;
    private javax.swing.JButton btnMasterJadwal1;
    private javax.swing.JButton btnMasterKelas;
    private javax.swing.JButton btnMasterKomputer;
    private javax.swing.JButton btnMasterSiswa;
    private javax.swing.JButton btnMasterUser;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel iconDashboard;
    private javax.swing.JLabel iconDriver;
    private javax.swing.JLabel iconDriver1;
    private javax.swing.JLabel iconDriver2;
    private javax.swing.JLabel iconJenis;
    private javax.swing.JLabel iconKelolaUser;
    private javax.swing.JLabel iconMenu;
    private javax.swing.JLabel iconOS;
    private javax.swing.JLabel iconProduk;
    private javax.swing.JLabel iconProdusen;
    private javax.swing.JLabel iconUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftHeader;
    private javax.swing.JPanel mark1;
    private javax.swing.JPanel mark2;
    private javax.swing.JPanel mark3;
    private javax.swing.JPanel mark4;
    private javax.swing.JPanel mark5;
    private javax.swing.JPanel mark6;
    private javax.swing.JPanel mark7;
    private javax.swing.JPanel mark8;
    private javax.swing.JPanel rightHeader;
    private javax.swing.JLabel textNama;
    private javax.swing.JLabel textRole;
    private javax.swing.JSplitPane topPanel;
    // End of variables declaration//GEN-END:variables
}
